<a href="https://colab.research.google.com/github/yoooobin/ESAA/blob/main/9_6_%EC%84%B8%EC%85%98_%EB%AC%B8%EC%A0%9C_%ED%92%80%EC%9D%B4_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np

A=np.random.random((5,3))
B=np.random.random((3,2))

np.dot(A,B)

array([[0.42058755, 0.67910335],
       [0.36929124, 0.9564194 ],
       [0.76884591, 0.99610237],
       [0.65186678, 1.04562867],
       [0.77106961, 0.97195565]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np

A = np.arange(10)
print(A)
A[(3<A)&(A<8)] = A[(3<A)&(A<8)]*-1
print(A)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   9 -> 0,1,2,3,4를 합한 값에 -1을 더해서 9가 나온다
*   10 -> -1을 축으로 보아야 하기때문에 10이 나온다


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

*   Legal: Z**Z, 2 << Z >> 2`, 1j * Z, Z / 1 / 1
*   Illegal: Z <- Z, Z < Z > Z


*   파이썬에서 대입 연산자는 <-가 아닌 =이다
*   파이썬에서 체인 비교는 불가능하다

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

*   1. 0으로 나누는 것은 정의되지 않기 때문에 nan
*   2. 0으로 나누는 것은 정의되지 않기 때문에 nan
*   3. nan의 형태를 변환할 수 없으므로 오류


In [31]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-31-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print("common_values:", common_values)

Z1: [1 1 0 3 3 5 0 0 6 7]
Z2: [3 1 0 6 8 1 3 5 5 0]
common_values: [0 1 3 5 6]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1)
np.emath.sqrt(-1)

<ipython-input-32-deadca2c2cb6>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-32-deadca2c2cb6>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


1j

False, np.sqrt(-1)는 nan을 반환하고, np.emath.sqrt(-1)는 복소수 1j를 반환하므로 false이다

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [33]:
import numpy as np

dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
import numpy as np

A = np.array([1, 2, 3, 4], dtype=float)
B = np.array([5, 6, 7, 8])

np.add(A, B, out=A)
np.divide(-A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, A, out=A)

print(A)

[ 9. 16. 25. 36.]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [34]:
A = np.random.uniform(0,10,10)
print(A)

print(A - A%1)
print(A // 1)

[9.05649499 6.84993712 6.17963355 0.10840693 7.82580254 0.46433379
 0.22683407 9.73385276 9.5743329  8.00608421]
[9. 6. 6. 0. 7. 0. 0. 9. 9. 8.]
[9. 6. 6. 0. 7. 0. 0. 9. 9. 8.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
import numpy as np
row_values = np.tile(np.arange(5), (5, 1))
print(row_values)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[0 1 2 3 4]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
A = np.random.random(10)
sorted_A = np.sort(A)

print(A)
print(sorted_A)

[0.62983085 0.0162409  0.00218153 0.17514546 0.25352268 0.36323569
 0.14527501 0.45201076 0.45178436 0.67761836]
[0.00218153 0.0162409  0.14527501 0.17514546 0.25352268 0.36323569
 0.45178436 0.45201076 0.62983085 0.67761836]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [35]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A)
print(B)
np.array_equal(A,B)

[0 0 0 1 1]
[0 0 0 0 0]


False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
cartesian = np.random.rand(10, 2) * 10
print("cartesian coordinates:\n", cartesian)

x = cartesian[:, 0] #x좌표
y = cartesian[:, 1] #y좌표

r = np.sqrt(x**2 + y**2) #반지름r = sqrt(x^2 + y^2) 식 이용
theta = np.arctan2(y, x) #각도 계산

polar_coordinates = np.column_stack((r, theta))
print("\n극좌표 (r, θ):\n", polar_coordinates)

cartesian coordinates:
 [[3.97096729 8.86177003]
 [5.41767121 7.88907098]
 [0.11378617 2.10660813]
 [6.78528844 6.33171341]
 [3.4397138  6.74278716]
 [8.33196353 4.75628053]
 [7.35645109 7.63138297]
 [8.67266208 5.73119344]
 [6.85830609 6.96213886]
 [5.14680334 1.33457182]]

극좌표 (r, θ):
 [[ 9.7107955   1.1495228 ]
 [ 9.57019343  0.96903122]
 [ 2.10967891  1.51683484]
 [ 9.28066452  0.75083277]
 [ 7.56946562  1.09907574]
 [ 9.59394708  0.51870796]
 [10.59978201  0.80373978]
 [10.39527036  0.583954  ]
 [ 9.77280615  0.79291101]
 [ 5.3170167   0.25371331]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.4062809  0.60463792 0.56125191 0.0890245  0.39972595 0.
 0.05621648 0.74840714 0.11041563 0.4955431 ]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z)
print(v)

distances = np.abs(Z - v)
closest_index = np.argmin(distances)
closest_value = Z[closest_index]

print(closest_value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
7.998898108537611
8


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
import numpy as np
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 5
p = 8
Z = np.zeros((n, n))

indices = np.random.choice(range(n * n), p, replace=False)
np.put(Z, indices, 1)

print(Z)

[[0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
print("원래 배열:\n", Z)

원래 배열:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# column 1
n = 1
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

1번째 열을 기준으로 정렬된 배열:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# column 2
n = 2
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

2번째 열을 기준으로 정렬된 배열:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# column 3
n = 3
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

3번째 열을 기준으로 정렬된 배열:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
