# Numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100.



File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    vers

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
null_vector_memory_size = null_vector.nbytes
print(null_vector_memory_size)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector6 = np.arange(start=10, stop=50)
print(vector6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector7 = np.sort(vector6)[::-1]
print(vector7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix8 = np.arange(0,9).reshape(3,3)
print(matrix8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)[0]
print(indices)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
matrix10 = np.identity(3)
print(matrix10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
matrix11 = np.random.random((3,3,3))
print(matrix11)

[[[0.65253101 0.45424753 0.48286417]
  [0.33871946 0.88069906 0.65084038]
  [0.67913716 0.05109124 0.68495928]]

 [[0.75742246 0.22698942 0.16463019]
  [0.87356608 0.25581612 0.68629608]
  [0.26531347 0.25576787 0.74783309]]

 [[0.01138919 0.94960096 0.57409845]
  [0.51702319 0.67566258 0.94066697]
  [0.54650423 0.50399298 0.87734216]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array12 = np.random.random((10,10))
print(array12)
print('min value:\n', array12.min())
print('max value:\n', array12.max())

[[7.18741666e-01 7.09632231e-01 9.34311553e-01 2.46053956e-01
  5.28665341e-01 2.24007624e-02 3.77487505e-01 3.03700489e-01
  8.30418112e-01 2.08990957e-01]
 [5.58757772e-01 9.54037769e-02 4.39417547e-01 4.97398737e-01
  6.90418511e-01 6.88523217e-01 6.08212662e-01 9.23731551e-01
  4.76803695e-01 4.14068321e-01]
 [7.89810933e-01 1.54176751e-01 1.12104701e-01 5.44220124e-01
  4.29863459e-01 2.34750994e-01 9.82173931e-01 7.47187572e-01
  3.05879129e-01 6.95430535e-01]
 [4.72905304e-01 1.40425672e-01 4.21687792e-01 2.95500192e-01
  3.86376687e-02 2.79242411e-01 1.04691969e-01 9.74417280e-02
  2.63495648e-01 7.48813342e-01]
 [1.22004323e-01 5.59378038e-01 2.46923573e-01 2.09252162e-01
  7.29117523e-01 4.70075563e-01 4.70458028e-01 4.34045159e-01
  8.85959071e-01 4.43331399e-01]
 [1.02790635e-01 2.14753593e-01 8.69794027e-01 6.85834846e-01
  7.02964220e-02 4.46556834e-02 3.14073051e-01 4.60866870e-01
  3.90451599e-01 6.65168155e-01]
 [8.47435081e-01 6.99509253e-02 3.51867865e-01 3.00398644e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array13 = np.random.random(30)
print(array13)
print('mean value:\n', array13.mean())

[0.80761731 0.58712602 0.32384393 0.80047888 0.40624702 0.70070228
 0.82894214 0.94651806 0.90493858 0.71089554 0.3167719  0.94466243
 0.04334827 0.7601002  0.37117013 0.88468466 0.5843804  0.74383755
 0.25817095 0.03613876 0.26491496 0.49687807 0.65361467 0.88630685
 0.28139646 0.51371266 0.93622455 0.79679797 0.11731111 0.2546685 ]
mean value:
 0.5720800277612874


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array14 = np.zeros((5,5))
array14[0, :] = 1
array14[:, 0] = 1
array14[4, :] = 1
array14[:, 4] = 1
print(array14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan

False

False

nan

False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix16 = np.zeros((5,5))
matrix16[1, 0] = 1
matrix16[2, 1] = 2
matrix16[3, 2] = 3
matrix16[4, 3] = 4
print(matrix16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix17 = np.zeros((8, 8))
matrix17[::2, ::2] = 1
matrix17[1::2, 1::2] = 1
print(matrix17)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
random_matrix = np.random.random((5,5))
Xbar = random_matrix.mean()
Std = random_matrix.std()
normalize_matrix = (random_matrix-Xbar)/Std
print(normalize_matrix)

[[ 0.5491856  -1.60911418  0.48864033  1.13336285 -0.49044939]
 [-0.6123796   0.23869093  0.62339405 -1.21163212 -0.34781608]
 [ 0.0532711  -0.4878615   0.50447644 -1.51074033  0.99453987]
 [ 1.57680847  0.51291243  1.60186891  0.77947211 -1.57381785]
 [-1.60751148 -0.49987356  0.72094423 -1.0086849   1.18231368]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
RGBA_dtype = np.dtype([('Red', np.ubyte), ('Green', np.ubyte), ('Blue', np.ubyte), ('Alpha', np.ubyte)])
print(RGBA_dtype)

[('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')]
